### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by grant-bowers** [awalvie/go-blender#4]
How does one use this to make a static site? I am trying to make one similar to @awalvie, but I can't figure out how to use this static site generator (the README just says stuff about it and the steps explain how it works).
(I apologize for being a programming newbie)

**Comment by awalvie** [comment]
Hey @OthoXYZ thanks for the issue. I've update the readme with the setup steps. `go-blender` is not a generally usable static site generator but was specifically created for my personal site, so it might not be very flexible, but feel free to open more issues if you have any questions or feature requests.
